# Use a base node image
FROM node:18-alpine

WORKDIR /app

# Set environment variable for chokidar (used by CRA for watching files)
ENV CHOKIDAR_USEPOLLING=true


# Copy package.json and package-lock.json to utilize Docker cache
COPY package.json package-lock.json ./

# Install npm globally in the container
RUN npm install

# Copy the rest of the application files
COPY . .

# This command will be used to start the React dev server
CMD ["npm", "run", "start"]

