# Use a base node image
FROM node:20-alpine

WORKDIR /app

# Set environment variable for chokidar (used by Next.js for watching files)
ENV CHOKIDAR_USEPOLLING=true

# Copy package.json and package-lock.json to utilize Docker cache
COPY package.json package-lock.json ./
