# Use a base node image
FROM node:20-alpine

WORKDIR /app

# Set environment variable for chokidar (used by Next.js for watching files)
ENV CHOKIDAR_USEPOLLING=true

# Copy both lucidify and lucidify-chat into the image
COPY lucidify /app
COPY lucidify-chat /lucidify-chat

# Install dependencies
RUN npm install

# This command will be used to start the Next.js dev server
CMD ["npm", "run", "dev"]

